local E, L, V, P, G = unpack(ElvUI);

P.addOnSkins = {
	skadaTemplate = "Default",
	skadaTemplateGloss = false,
	skadaTitleTemplate = "Default",
	skadaTitleTemplateGloss = true,

	dbmBarHeight = 22,
	dbmFont = "PT Sans Narrow",
	dbmFontSize = 12,
	dbmFontOutline = "OUTLINE",

	weakAuraAuraBar = true,
	weakAuraIconCooldown = true,

	chatBarSize = 16,
	chatBarSpacing = 1,
	chatBarTextPoint = "LEFT",
	chatBarTextXOffset = -3,
	chatBarTextYOffset = 0,

	embed = {
		embedType = "DISABLE",
		left = "Skada",
		right = "Skada",
		rightChat = true,
		leftWidth = 200,
		belowTop = false,
		hideChat = "NONE",
		isShow = true,
	}
};

V.addOnSkins = {
	Omen = true,
	Recount = true,
	SexyCooldown = true,
	DBM = true,
	Skada = true,
	Auctionator = true,
	BugSack = true,
	CallToArms = true,
	Postal = true,
	QuestPointer = true,
	Clique = true,
	FloAspectBar = true,
	FloTotemBar = true,
	Spy = true,
	AtlasLoot = true,
	Atlas = true,
	FlightMap = true,
	WeakAuras = true,
	Overachiever = true,
	OpenGF = true,
	KHunterTimers = true,
	TellMeWhen = true,
	GearScore = true,
	AllStats = true,
	BlackList = true,
	GnomishVendorShrinker = true,
	ACP = true,
	EveryQuest = true,
	_NPCScan = true,
	MoveAnything = true,
	VanasKoS = true,
	BindPad = true,
	ZygorGuidesViewer = true,
	ZygorTalentAdvisor = true,
	WowLua = true,
	ChatBar = true,
	Skillet = true,
	TotemTimers = true,
	PlateBuffs = true,
	MageNuggets = true,
	InspectEquip = true,
	AdvancedTradeSkillWindow = true,
	AtlasQuest = true,
	AckisRecipeList = true,
	LightHeaded = true,
	Carbonite = true,
	Enchantrix = true,
	FishingBuddy = true,
	Talented = true,
	TinyPad = true,
	ZOMGBuffs = true,
	BuyEmAll = true,
	Doom_CooldownPulse = true,
	AdiBags = true,
	PallyPower = true,
	KarniCrap = true,
	TradeskillInfo = true,
	PAB = true,
	EPGP = true,
	EPGP_LootMaster = true,
	RaidRoll = true,
	RaidCooldowns = true,

	Blizzard_WorldStateFrame = true,
};
